# Generated by Django 6.1 on 2026-08-09 09:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinteraction',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddConstraint(
            model_name='userinteraction',
            constraint=models.UniqueConstraint(fields=('user', 'course_id'), name='unique_user_course'),
        ),
    ]
